"""Add user and folio relationship, update scheme folio fk and valuation columns (again)

Revision ID: 8756e2d1f258
Revises: d32b9149cada
Create Date: 2025-03-04 03:40:52.101548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8756e2d1f258'
down_revision: Union[str, None] = 'd32b9149cada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folio',
    sa.Column('statement_period_id', sa.Integer(), nullable=True),
    sa.Column('folio_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('amc', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['statement_period_id'], ['statement_period.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('folio_number'),
    sa.UniqueConstraint('folio_number', name='uq_folio_statement_period')
    )
    op.create_index(op.f('ix_folio_folio_number'), 'folio', ['folio_number'], unique=False)
    op.create_table('scheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_id', sa.String(), nullable=True),
    sa.Column('scheme_name', sa.String(), nullable=True),
    sa.Column('advisor', sa.String(), nullable=True),
    sa.Column('rta_code', sa.String(), nullable=True),
    sa.Column('rta', sa.String(), nullable=True),
    sa.Column('scheme_type', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('amfi_code', sa.String(), nullable=True),
    sa.Column('nominees', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('open_units', sa.Float(), nullable=True),
    sa.Column('close_units', sa.Float(), nullable=True),
    sa.Column('close_calculated_units', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['folio_id'], ['folio.folio_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio_id', 'scheme_name', name='uq_scheme_folio')
    )
    op.create_index(op.f('ix_scheme_id'), 'scheme', ['id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('dividend_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=True),
    sa.Column('valuation_nav', sa.Float(), nullable=True),
    sa.Column('valuation_cost', sa.Float(), nullable=True),
    sa.Column('valuation_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuation')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_scheme_id'), table_name='scheme')
    op.drop_table('scheme')
    op.drop_index(op.f('ix_folio_folio_number'), table_name='folio')
    op.drop_table('folio')
    op.drop_table('statement_period')
    # ### end Alembic commands ###
