"""Add user_id to StatementPeriod

Revision ID: 92b205d2adea
Revises: 8756e2d1f258
Create Date: 2025-03-06 21:58:06.338866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b205d2adea'
down_revision: Union[str, None] = '8756e2d1f258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statement_period', sa.Column('user_id', sa.String(), nullable=True))
    op.create_unique_constraint('uq_statement_period_user', 'statement_period', ['user_id', 'from_date', 'to_date'])
    op.create_foreign_key(None, 'statement_period', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statement_period', type_='foreignkey')
    op.drop_constraint('uq_statement_period_user', 'statement_period', type_='unique')
    op.drop_column('statement_period', 'user_id')
    op.drop_constraint('uq_folio_statement_period', 'folio', type_='unique')
    # ### end Alembic commands ###
