"""empty message

Revision ID: a09fb6f89f33
Revises: af8c5771166e
Create Date: 2025-03-12 14:47:14.178253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09fb6f89f33'
down_revision: Union[str, None] = 'af8c5771166e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('amc_amfi_code_key', 'amc', type_='unique')
    op.drop_constraint('amc_isin_key', 'amc', type_='unique')
    op.drop_column('amc', 'isin')
    op.drop_column('amc', 'amfi_code')
    op.add_column('scheme', sa.Column('amc_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'scheme', 'amc', ['amc_id'], ['id'])
    op.create_foreign_key(None, 'scheme', 'folio', ['folio_id'], ['folio_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheme', type_='foreignkey')
    op.drop_constraint(None, 'scheme', type_='foreignkey')
    op.drop_column('scheme', 'amc_id')
    op.add_column('amc', sa.Column('amfi_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('amc', sa.Column('isin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('amc_isin_key', 'amc', ['isin'])
    op.create_unique_constraint('amc_amfi_code_key', 'amc', ['amfi_code'])
    # ### end Alembic commands ###
