"""empty message

Revision ID: af8c5771166e
Revises: d16d7cbed65e
Create Date: 2025-03-12 14:13:11.818123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8c5771166e'
down_revision: Union[str, None] = 'd16d7cbed65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE folio DROP CONSTRAINT uq_folio_statement_period CASCADE")
    op.create_unique_constraint('uq_folio_statement_period', 'folio', ['folio_number'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_folio_statement_period', 'folio', type_='unique')
    # ### end Alembic commands ###
